# Python basics for DL newbies

In [ ]:
import numpy as np
import torch
n_array = np.arange(10).reshape(2, 5)
t_array = torch.FloatTensor(n_array)
print(f"ndim : {t_array}, shape : {t_array.shape}")

ndim : tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]), shape : torch.Size([2, 5])


## Tensor생성은 list나 ndarray 사용가능

In [ ]:
# 잘 사용 안 함
# data to tensor
data = [[3, 5], [10, 5]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [ ]:
# 잘 사용 안 함
# ndarry to tensor
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

## 기본적으로 **numpy**의 대부분의 사용법이 그대로 적용됨

In [ ]:
data = [[3, 5, 10], [10, 5, 50], [1, 5, 10]]
x_data = torch.tensor(data)
x_data

tensor([[ 3,  5, 10],
        [10,  5, 50],
        [ 1,  5, 10]])

slicing

In [ ]:
x_data[1:] # 1행부터 열 전체
# tensor([[ 3,  5, 10],
#         [10,  5, 50],
#         [ 1,  5, 10]])

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [ ]:
x_data[:2, 1:] # 0행과 1행 + 1열~마지막열

tensor([[ 5, 10],
        [ 5, 50]])

flatten()

In [ ]:
x_data.flatten()

tensor([ 3,  5, 10, 10,  5, 50,  1,  5, 10])

something_like
> 같은 크기의 텐서를 만들어주고 1로 채워넣음


In [ ]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

텐서를 넘파이로 변환 / 텐선의 행과 열/ 타입

In [ ]:
x_data.numpy()

array([[ 3,  5, 10],
       [10,  5, 50],
       [ 1,  5, 10]])

In [ ]:
x_data.shape
# shape할 때 괄호 주의하기

torch.Size([3, 3])

In [ ]:
x_data.dtype
x_data

tensor([[ 3,  5, 10],
        [10,  5, 50],
        [ 1,  5, 10]])

pytorch의 tensor는 GPU에 올려 사용가능

In [ ]:
x_data.device

device(type='cpu')

In [ ]:
# device(type = 'cpu')
if torch.cuda.is_available():
  x_data_cuda = x_data.to("cuda")

x_data_cuda.device
# device(type = 'cuda')

device(type='cuda', index=0)

#Tensor handling
- view, squeeze, unsqueez 등으로 tensor 조정가능
  - view : reshape과 동일하게 tensor의 shape을 변환
  - squeeze : 차원의 개수가 1인 차원을 삭제(압축)
  - unsqeeze : 차원의 개수가 1인 차원을 추가

- view 와 reshape의 차이점
  - view : call by referenc : 원본의 영향받음
  - reshape : call by value : 원본의 영향을 받지 아니함. > copy를 해버림.

In [ ]:
tensor_ex = torch.rand(size= (2, 3, 4))
tensor_ex
# count 24

tensor([[[0.8656, 0.0558, 0.5387, 0.2805],
         [0.4492, 0.3002, 0.7474, 0.3055],
         [0.6632, 0.4475, 0.6510, 0.5491]],

        [[0.7770, 0.5705, 0.6596, 0.7970],
         [0.6873, 0.3728, 0.0309, 0.3026],
         [0.8898, 0.8770, 0.2875, 0.3447]]])

In [ ]:
tensor_ex.shape

torch.Size([2, 3, 4])

In [ ]:
tensor_ex.view([-1, 6])
# count 24 이므로 -1인 4에 해당

tensor([[0.8656, 0.0558, 0.5387, 0.2805, 0.4492, 0.3002],
        [0.7474, 0.3055, 0.6632, 0.4475, 0.6510, 0.5491],
        [0.7770, 0.5705, 0.6596, 0.7970, 0.6873, 0.3728],
        [0.0309, 0.3026, 0.8898, 0.8770, 0.2875, 0.3447]])

In [ ]:
tensor_ex.view([-1, 6]).shape

torch.Size([4, 6])

In [ ]:
a = torch.zeros(3, 2)
b = a.view(2, 3) # a를 카피했다면 a.fill_(1)을 해도 b는 0으로 가득차있어야한다.
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
_b # 그런데 b가 1로 차있다는건 call by refernce 주소값 참조를 해서 원보의 영향을 받은 상태이다.

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
a = torch.zeros(3, 2)
b = a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
b

tensor([0., 0., 0., 0., 0., 0.])

squeeze, unsqueeze
- [[1, 2], [3 ,4]] (2, 2)
->unsqueezz(0):(***1***, 2, 2) ->squeeze():(2, 2)
->unsqueezz(1):(2, ***1*** ,2)->squeeze():(2, 2)
->unsqueezz(2):(2, 2, ***1***)->squeeze():(2, 2)

In [ ]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex.squeeze()
# (2, 1, 2) -> (2. 2)

tensor([[0.5347, 0.1465],
        [0.9674, 0.0391]])

In [ ]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(0).shape
# (2, 2) -> (1, 2, 2)

torch.Size([1, 2, 2])

In [ ]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(1).shape
# (2, 2) -> (2, 1, 2)

torch.Size([2, 1, 2])

In [ ]:
tensor_ex = torch.rand(size=(2, 2))
tensor_ex.unsqueeze(2).shape
# (2, 2) -> (2, 2, 1)

torch.Size([2, 2, 1])

## Tensor operation
- 기본적으로 tensor의 operation는 numpy와 동일
- **행렬곱셈연산은 dot(벡터내적)이 아닌 mm(행력곱) 사용**


In [ ]:
n1 = np.arange(10).reshape(2, 5)
t1 = torch.FloatTensor(n1)
n2 = np.arange(10).reshape(5, 2)
t2 = torch.FloatTensor(n2)


In [ ]:
t1

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [ ]:
t2

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [ ]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

* 정리
! **reshape 보다는 view를 쓰자**
! **dot 보다는 mm을 쓰자**
** matmul - 브로드캐스팅 지원 **

In [ ]:
t2.mm(t1)

tensor([[  5.,   6.,   7.,   8.,   9.],
        [ 15.,  20.,  25.,  30.,  35.],
        [ 25.,  34.,  43.,  52.,  61.],
        [ 35.,  48.,  61.,  74.,  87.],
        [ 45.,  62.,  79.,  96., 113.]])

3차원 곱셉
(1, 1, 2) * (1, 2, 1) = (1, 2, 2)

In [ ]:
a = torch.rand(5, 2, 3)
b = torch.rand(3)
# a.mm(b)
c = a.matmul(b)
c

# 5(배치) (2, 3) * (3, 1) = (배치:5, 2, 1)

tensor([[1.6894, 0.6453],
        [0.9544, 0.7717],
        [1.4592, 0.7349],
        [1.0678, 1.9023],
        [1.0189, 0.3509]])

In [ ]:
a[0].mm(torch.unsqueeze(b, 1))

tensor([[1.6894],
        [0.6453]])

In [ ]:
a[1].mm(torch.unsqueeze(b, 1))

tensor([[0.9544],
        [0.7717]])

In [ ]:
a[2].mm(torch.unsqueeze(b, 1))


tensor([[1.4592],
        [0.7349]])

In [ ]:
a[3].mm(torch.unsqueeze(b, 1))


tensor([[1.0678],
        [1.9023]])

In [ ]:
a[4].mm(torch.unsqueeze(b, 1))

tensor([[1.0189],
        [0.3509]])

In [ ]:
a[0].mm(torch.unsqueeze(b, 1)).squeeze()

tensor([1.6894, 0.6453])

# Tensor operations for ML/DL formula
- nn.fucntional 모듈을 통해 다양한 수식 변환을 지원함

In [7]:
import torch
import torch.nn.functional as F

In [8]:
tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor = F.softmax(tensor, dim = 0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [12]:
y = torch.randint(5, (10,5))
print(y)
y_label = y.argmax(dim = 1) # 행에서 가장 큰 값을 가지는 인덱스 반환
y_label

tensor([[2, 2, 3, 0, 3],
        [4, 3, 3, 3, 0],
        [3, 2, 2, 1, 0],
        [1, 2, 3, 2, 1],
        [0, 4, 0, 2, 1],
        [3, 3, 1, 4, 2],
        [2, 2, 1, 3, 3],
        [4, 4, 3, 2, 4],
        [4, 0, 4, 3, 1],
        [1, 4, 4, 1, 3]])


tensor([2, 0, 0, 2, 1, 3, 3, 0, 0, 1])

In [13]:
torch.nn.functional.one_hot(y_label)

tensor([[0, 0, 1, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0]])

# AutoGrad
- pytorch의 핵심은 자동미분의 지원 -> backward함수사용
---
$$
y = w^2 \\
z = 10y + 25 \\
z =10w^2 + 25
$$

In [16]:
w = torch.tensor(2.0, requires_grad = True)
y = w ** 2
z = 10 * y + 25
z.backward()
w.grad

tensor(40.)

$$Q = 3a^3 - b^2$$

In [19]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.])
Q.backward(gradient = external_grad)

a.grad

tensor([36., 81.])

$$ \frac{∂Q}{∂a} = 9a^2$$
$$ \frac{\partial Q}{\partial b} = -2b $$

In [20]:
b.grad

tensor([-12.,  -8.])